# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://insideidaho.org
#url: https://inside-new.nkn.uidaho.edu
# location on the domain
# e.g. /digital/hjccc
baseurl: 
# repository
source-code: https://github.com/uidaholib/inside_source

# Site settings
title: INSIDE Idaho
# header and head metadata
tagline: Idaho's Geospatial Data Clearinghouse
description: "INSIDE Idaho is the geospatial data clearinghouse for the State of Idaho recognized by the Idaho Geospatial Council - Executive Committee. INSIDE Idaho serves as a data digital library, providing access to, and a context within which to use, geospatial data and information by, for, and about Idaho." 
email: bgodfrey@uidaho.edu
# for markup 
featured-image: "/assets/img/transparent_header.png"
featured-image-alt: "INSIDE Idaho"

# Organization branding
organization-name: "INSIDE Idaho"
organization-link: /
organization-logo-banner: /assets/img/transparent_header.png
organization-logo-nav: /assets/img/transparent_header.png

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: 

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
